on:
  # Trigger the workflow on push,
  # but only for the main branch
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install and Test
        run: |
          npm ci
          npm run eslint
          npm test
